<a href="https://colab.research.google.com/github/themuditjain/Ranking-Products/blob/main/Assigned_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing the libraries

In [ ]:
import pandas as pd
import numpy as np
import io

**Uploading the file**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving 1091_2022-11-01.csv to 1091_2022-11-01 (1).csv


**Printing of the dataset**

In [ ]:
df = pd.read_csv(io.BytesIO(uploaded['1091_2022-11-01.csv']))
print(df)

         Sku  Click Cnt  Sale Qty  Live Stock  Initital Stock  Size Count  \
0     101478          0         0           2               0         2.0   
1     101505          0         0           0               0         0.0   
2     101479        105         2          44              59         3.0   
3     101506        207         3          49              45         2.0   
4     101480        192         7         224             244         3.0   
...      ...        ...       ...         ...             ...         ...   
6246  104601          0         0           0               0         NaN   
6247  104628          0         0           0               0         NaN   
6248  104602          0         0           0               0         NaN   
6249  104629          0         0           0               0         NaN   
6250  104603          0         0           0               0         NaN   

                 Offer    Category          Brand  MRP  Special Price  Padd

**Dropping the columns which are not required**

In [ ]:
to_drop = ['Sku']
df.drop(to_drop, inplace=True, axis=1)

In [ ]:
# print(df)

In [ ]:
to_drop1 = ['Special Price']
df.drop(to_drop1, inplace=True, axis=1)

In [ ]:
# print(df)

**Check for null row by row**

In [ ]:
df.isnull()

Click Cnt  Sale Qty  Live Stock  Initital Stock  Size Count  Offer  \
0         False     False       False           False       False  False   
1         False     False       False           False       False  False   
2         False     False       False           False       False  False   
3         False     False       False           False       False  False   
4         False     False       False           False       False  False   
...         ...       ...         ...             ...         ...    ...   
6246      False     False       False           False        True   True   
6247      False     False       False           False        True   True   
6248      False     False       False           False        True   True   
6249      False     False       False           False        True   True   
6250      False     False       False           False        True   True   

      Category  Brand    MRP  Padded  
0        False   True  False    True  
1        False   True  False    True  
2        False  False  False   False  
3        False  False  False   False  
4        False  False  False   False  
...        ...    ...    ...     ...  
6246     False  False  False    True  
6247     False  False  False    True  
6248     False  False  False    True  
6249     False  False  False    True  
6250     False  False  False    True  

[6251 rows x 10 columns]

In [ ]:
df.describe()

Click Cnt     Sale Qty   Live Stock  Initital Stock   Size Count  \
count   6251.000000  6251.000000  6251.000000     6251.000000  6035.000000   
mean      86.087186     2.949768    86.470325      100.340106     1.258161   
std      522.726289    17.855976   349.645850      395.200477     3.422318   
min        0.000000     0.000000    -9.000000        0.000000     0.000000   
25%        0.000000     0.000000     0.000000        0.000000     0.000000   
50%        0.000000     0.000000     0.000000        0.000000     0.000000   
75%        1.000000     0.000000     0.000000        0.000000     0.000000   
max    25450.000000   817.000000  3744.000000     3891.000000    28.000000   

               MRP  
count  6251.000000  
mean    626.534794  
std     332.539953  
min       0.000000  
25%     299.000000  
50%     649.000000  
75%     799.000000  
max    2350.000000

**Check for null values**

In [ ]:
df.isnull().sum()

Click Cnt            0
Sale Qty             0
Live Stock           0
Initital Stock       0
Size Count         216
Offer             3285
Category             0
Brand                7
MRP                  0
Padded            3111
dtype: int64

**Replacing the null values by mean**

In [ ]:
df['Size Count'].replace([np.nan], df['Size Count'].mean(), inplace=True)

In [ ]:
df.isnull().sum()

Click Cnt            0
Sale Qty             0
Live Stock           0
Initital Stock       0
Size Count           0
Offer             3285
Category             0
Brand                7
MRP                  0
Padded            3111
dtype: int64

**Replacing the null values by mode as they are of type string**

In [ ]:
df['Padded'] = df['Padded'].fillna(df['Padded'].mode()[0])

In [ ]:
df.isnull().sum()

Click Cnt            0
Sale Qty             0
Live Stock           0
Initital Stock       0
Size Count           0
Offer             3285
Category             0
Brand                7
MRP                  0
Padded               0
dtype: int64

In [ ]:
df['Brand'] = df['Brand'].fillna(df['Brand'].mode()[0])
df['Offer'] = df['Offer'].fillna(df['Offer'].mode()[0])

In [ ]:
df.isnull().sum()

Click Cnt         0
Sale Qty          0
Live Stock        0
Initital Stock    0
Size Count        0
Offer             0
Category          0
Brand             0
MRP               0
Padded            0
dtype: int64

**Printing the database after filtering the dataset**

In [ ]:
print(df)

      Click Cnt  Sale Qty  Live Stock  Initital Stock  Size Count  \
0             0         0           2               0    2.000000   
1             0         0           0               0    0.000000   
2           105         2          44              59    3.000000   
3           207         3          49              45    2.000000   
4           192         7         224             244    3.000000   
...         ...       ...         ...             ...         ...   
6246          0         0           0               0    1.258161   
6247          0         0           0               0    1.258161   
6248          0         0           0               0    1.258161   
6249          0         0           0               0    1.258161   
6250          0         0           0               0    1.258161   

                 Offer    Category          Brand  MRP  Padded  
0     Buy 1 Get 1 Free         Bra          Shyle  100  Padded  
1     Buy 1 Get 1 Free         Bra       

In [ ]:
df1=df[df['MRP']>0]

In [ ]:
df['MRP'].describe()

count    6251.000000
mean      626.534794
std       332.539953
min         0.000000
25%       299.000000
50%       649.000000
75%       799.000000
max      2350.000000
Name: MRP, dtype: float64

# **Best Selling Offer**

In [ ]:
df.groupby(["Offer", "MRP"]).size()

Offer             MRP 
Buy 1 Get 1 Free  0        1
                  100      1
Buy 2 For 1049    199      4
                  549      6
                  599      2
                          ..
Flat 20           1599     5
Flat 30           1495     1
                  1739     1
Flat 40           699     48
                  999     19
Length: 218, dtype: int64

In [ ]:
df2=df.groupby(["Offer", "MRP"]).size().reset_index(name="Time")

In [ ]:
df2

Offer   MRP  Time
0    Buy 1 Get 1 Free     0     1
1    Buy 1 Get 1 Free   100     1
2      Buy 2 For 1049   199     4
3      Buy 2 For 1049   549     6
4      Buy 2 For 1049   599     2
..                ...   ...   ...
213           Flat 20  1599     5
214           Flat 30  1495     1
215           Flat 30  1739     1
216           Flat 40   699    48
217           Flat 40   999    19

[218 rows x 3 columns]

**Printing the new dataset having the Best Selling offer details**

In [ ]:
df2

Offer   MRP  Time
0    Buy 1 Get 1 Free     0     1
1    Buy 1 Get 1 Free   100     1
2      Buy 2 For 1049   199     4
3      Buy 2 For 1049   549     6
4      Buy 2 For 1049   599     2
..                ...   ...   ...
213           Flat 20  1599     5
214           Flat 30  1495     1
215           Flat 30  1739     1
216           Flat 40   699    48
217           Flat 40   999    19

[218 rows x 3 columns]

In [ ]:
df.groupby(["Offer", "MRP"]).size().max()

1640

In [ ]:
df.loc[df.groupby(["Offer", "MRP"]).size().max()]

Click Cnt                     0
Sale Qty                      0
Live Stock                    0
Initital Stock                0
Size Count                  0.0
Offer             Buy 5 For 599
Category                  Panty
Brand                     Shyle
MRP                         299
Padded                   Padded
Name: 1640, dtype: object

*Above query clearly shows that the best selling offer is Buy 5 For 599 when the MRP is 299*

# **Best Selling Period**

*y is the dataset having the best selling offer dteails so it is used to find the best selling period when the average of best selling offer respective to each column has been used*

In [ ]:
y=df[(df['Offer']=='Buy 5 For 599' ) & (df['MRP']==299)]
print(y)

      Click Cnt  Sale Qty  Live Stock  Initital Stock  Size Count  \
1223          0         0           0               0    0.000000   
1224          0         0           0               0    0.000000   
1225          0         0           0               0    0.000000   
1226          0         0           0               0    0.000000   
1227          0         0           0               0    0.000000   
...         ...       ...         ...             ...         ...   
6080          0         0           0               0    1.258161   
6101          0         0           0               0    1.258161   
6102          0         0           0               0    1.258161   
6103          0         0           0               0    1.258161   
6113        417         8         377             402    1.258161   

              Offer     Category  Brand  MRP  Padded  
1223  Buy 5 For 599        Panty  Shyle  299  Padded  
1224  Buy 5 For 599        Panty  Shyle  299  Padded  
1225  

In [ ]:
y['Click Cnt'].mean()

7.487804878048781

In [ ]:
y['Sale Qty'].mean()

0.9103658536585366

In [ ]:
y['Live Stock'].mean()

38.985365853658536

In [ ]:
y['Initital Stock'].mean()

46.884756097560974

In [ ]:
y['Size Count'].mean()

0.26420170953987915

# **Size count availability**

In [ ]:
a=df[df['Size Count']>8]
print(a)

      Click Cnt  Sale Qty  Live Stock  Initital Stock  Size Count  \
202         283         2         174             180         9.0   
207         436        15         183             200        10.0   
209         562        15         160             180         9.0   
212         360        13         203             220        11.0   
213         161         4         214             220        11.0   
...         ...       ...         ...             ...         ...   
6047          0         0          99               0        20.0   
6048          0         0          99               0        20.0   
6049          0         0          95               0        19.0   
6050          0         0          95               0        19.0   
6051          0         0         100               0        20.0   

               Offer      Category  Brand  MRP      Padded  
202   Buy 2 For 1099  Lingerie Set  Taabu  999      Padded  
207   Buy 2 For 1099  Lingerie Set  Taabu  999   

In [ ]:
a.count()

Click Cnt         322
Sale Qty          322
Live Stock        322
Initital Stock    322
Size Count        322
Offer             322
Category          322
Brand             322
MRP               322
Padded            322
dtype: int64

# **Live Stock More than 250**

In [ ]:
x=df[df['Live Stock']>250]
print(x)

      Click Cnt  Sale Qty  Live Stock  Initital Stock  Size Count  \
251         425        14         377             409   18.000000   
253         212         1         310             340   18.000000   
254         154         2         380             384   18.000000   
255         150         5         371             393   18.000000   
257         112         2         438             451   18.000000   
...         ...       ...         ...             ...         ...   
5919          0         0        1076            1076    7.000000   
5922          0         0         271             271    5.000000   
5982          1         7        2481            1834    6.000000   
6073        205         5         333             374    1.258161   
6113        417         8         377             402    1.258161   

               Offer     Category  Brand  MRP      Padded  
251   Buy 2 For 1299          Bra  Susie  999  Non-Padded  
253   Buy 2 For 1299          Bra  Susie  999  Non-

In [ ]:
print(x.count())

Click Cnt         454
Sale Qty          454
Live Stock        454
Initital Stock    454
Size Count        454
Offer             454
Category          454
Brand             454
MRP               454
Padded            454
dtype: int64


# **Return Percentage less than 5%**

In [ ]:
z=df[df['Initital Stock']>0]

In [ ]:
print(z)

      Click Cnt  Sale Qty  Live Stock  Initital Stock  Size Count  \
2           105         2          44              59    3.000000   
3           207         3          49              45    2.000000   
4           192         7         224             244    3.000000   
11           80         7          26              49    3.000000   
16          196         2          14              17    1.000000   
...         ...       ...         ...             ...         ...   
6111        481        17          15              48    1.258161   
6113        417         8         377             402    1.258161   
6181         84         0          22              22    1.258161   
6190         76         2           6              11    1.258161   
6220        285         4          38              53    1.258161   

               Offer     Category          Brand  MRP  Padded  
2     Buy 2 For 1049   Sportswear  Liberti World  699  Padded  
3     Buy 2 For 1049   Sportswear  Liberti 

In [ ]:
z.count()

Click Cnt         1023
Sale Qty          1023
Live Stock        1023
Initital Stock    1023
Size Count        1023
Offer             1023
Category          1023
Brand             1023
MRP               1023
Padded            1023
dtype: int64

In [ ]:
z['diff'] = z['Initital Stock'] - (z['Live Stock'] + z['Sale Qty'])

<ipython-input-112-9c0e3095c5d6>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  z['diff'] = z['Initital Stock'] - (z['Live Stock'] + z['Sale Qty'])


In [ ]:
print(z['diff'])

2       13
3       -7
4       13
11      16
16       1
        ..
6111    16
6113    17
6181     0
6190     3
6220    11
Name: diff, Length: 1023, dtype: int64


In [ ]:
z['percent']=(z['diff'] / z['Initital Stock']) * 100.0

<ipython-input-114-b544be4a8aaf>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  z['percent']=(z['diff'] / z['Initital Stock']) * 100.0


In [ ]:
print(z)

      Click Cnt  Sale Qty  Live Stock  Initital Stock  Size Count  \
2           105         2          44              59    3.000000   
3           207         3          49              45    2.000000   
4           192         7         224             244    3.000000   
11           80         7          26              49    3.000000   
16          196         2          14              17    1.000000   
...         ...       ...         ...             ...         ...   
6111        481        17          15              48    1.258161   
6113        417         8         377             402    1.258161   
6181         84         0          22              22    1.258161   
6190         76         2           6              11    1.258161   
6220        285         4          38              53    1.258161   

               Offer     Category          Brand  MRP  Padded  diff    percent  
2     Buy 2 For 1049   Sportswear  Liberti World  699  Padded    13  22.033898  
3     Buy

In [ ]:
z['percent']

2       22.033898
3      -15.555556
4        5.327869
11      32.653061
16       5.882353
          ...    
6111    33.333333
6113     4.228856
6181     0.000000
6190    27.272727
6220    20.754717
Name: percent, Length: 1023, dtype: float64

**Return of items with respect to Category**

In [ ]:
z.groupby('Category')['percent'].mean()

Category
Accessories     17.075476
Bra             14.380143
Clothing        13.404001
Lingerie Set     1.333333
Nightwear       -1.496156
Panty           24.497406
Shapewear        6.187579
Sportswear      -0.603281
Name: percent, dtype: float64

**Return of items with respect to Offers**

In [ ]:
z.groupby('Offer')['percent'].mean()

Offer
Buy 2 For 1049                   12.786605
Buy 2 For 1099                    1.333333
Buy 2 For 1299                  -26.344507
Buy 2 For 599                    13.756263
Buy 2 Get 3 Free,Flat 50% Off    11.083986
Buy 3 For 599                    25.948660
Buy 4 For 999,Flat Rs.299        32.326247
Buy 5 For 599                    16.042048
Flat 20                         -13.844877
Name: percent, dtype: float64

**Total return of all items**

In [ ]:
z['percent'].mean()

12.455457345918626

# **Ranking the dataset accordingly to all the 5 parameters**

In [ ]:
df1

Click Cnt  Sale Qty  Live Stock  Initital Stock  Size Count  \
0             0         0           2               0    2.000000   
2           105         2          44              59    3.000000   
3           207         3          49              45    2.000000   
4           192         7         224             244    3.000000   
5             0         0           0               0    0.000000   
...         ...       ...         ...             ...         ...   
6246          0         0           0               0    1.258161   
6247          0         0           0               0    1.258161   
6248          0         0           0               0    1.258161   
6249          0         0           0               0    1.258161   
6250          0         0           0               0    1.258161   

                 Offer    Category          Brand  MRP  Padded  
0     Buy 1 Get 1 Free         Bra          Shyle  100  Padded  
2       Buy 2 For 1049  Sportswear  Liberti World  699  Padded  
3       Buy 2 For 1049  Sportswear  Liberti World  699  Padded  
4       Buy 2 For 1049  Sportswear  Liberti World  649  Padded  
5       Buy 2 For 1049  Sportswear          Shyle  999  Padded  
...                ...         ...            ...  ...     ...  
6246     Buy 5 For 599    Clothing          Shyle  249  Padded  
6247     Buy 5 For 599    Clothing          Shyle  249  Padded  
6248     Buy 5 For 599    Clothing          Shyle  249  Padded  
6249     Buy 5 For 599    Clothing          Shyle  249  Padded  
6250     Buy 5 For 599    Clothing          Shyle  249  Padded  

[6240 rows x 10 columns]

In [ ]:
tempdf=df1

In [ ]:
dff2 = tempdf.groupby(["Offer", "Category", "Brand", "MRP", "Padded"])

In [ ]:
tempdf=dff2.agg({'Click Cnt':'mean', 'Sale Qty':'mean','Live Stock':'mean','Initital Stock':'mean','Size Count':'mean'}).rename(columns={'Click Cnt':'Click Cnt', 'Sale Qty':'Sale Qty','Live Stock':'Live Stock', 'Initital Stock':'Initital Stock','Size Count':'Size Count'})

In [ ]:
tempdf['count'] = dff2.size()

In [ ]:
tempdf

Click Cnt  \
Offer            Category     Brand         MRP  Padded                  
Buy 1 Get 1 Free Bra          Shyle         100  Padded            0.0   
Buy 2 For 1049   Sportswear   Amante        995  Non-Padded        0.0   
                              Cross & Pearl 599  Non-Padded        0.0   
                              Jockey        199  Padded            0.0   
                                            549  Padded            0.0   
...                                                                ...   
Flat 30          Nightwear    Shyle         1495 Padded            0.0   
                                            1739 Padded            2.0   
Flat 40          Lingerie Set Susie         999  Padded            0.0   
                 Nightwear    Shyaway       699  Padded            0.0   
                                            999  Padded            0.0   

                                                             Sale Qty  \
Offer            Category     Brand         MRP  Padded                 
Buy 1 Get 1 Free Bra          Shyle         100  Padded           0.0   
Buy 2 For 1049   Sportswear   Amante        995  Non-Padded       0.0   
                              Cross & Pearl 599  Non-Padded       0.0   
                              Jockey        199  Padded           0.0   
                                            549  Padded           0.0   
...                                                               ...   
Flat 30          Nightwear    Shyle         1495 Padded           0.0   
                                            1739 Padded           0.0   
Flat 40          Lingerie Set Susie         999  Padded           0.0   
                 Nightwear    Shyaway       699  Padded           0.0   
                                            999  Padded           0.0   

                                                             Live Stock  \
Offer            Category     Brand         MRP  Padded                   
Buy 1 Get 1 Free Bra          Shyle         100  Padded        2.000000   
Buy 2 For 1049   Sportswear   Amante        995  Non-Padded    0.000000   
                              Cross & Pearl 599  Non-Padded    0.000000   
                              Jockey        199  Padded        0.000000   
                                            549  Padded        0.000000   
...                                                                 ...   
Flat 30          Nightwear    Shyle         1495 Padded        0.000000   
                                            1739 Padded        0.000000   
Flat 40          Lingerie Set Susie         999  Padded        0.000000   
                 Nightwear    Shyaway       699  Padded        0.020833   
                                            999  Padded        0.000000   

                                                             Initital Stock  \
Offer            Category     Brand         MRP  Padded                       
Buy 1 Get 1 Free Bra          Shyle         100  Padded                 0.0   
Buy 2 For 1049   Sportswear   Amante        995  Non-Padded             0.0   
                              Cross & Pearl 599  Non-Padded             0.0   
                              Jockey        199  Padded                 0.0   
                                            549  Padded                 0.0   
...                                                                     ...   
Flat 30          Nightwear    Shyle         1495 Padded                 0.0   
                                            1739 Padded                 0.0   
Flat 40          Lingerie Set Susie         999  Padded                 0.0   
                 Nightwear    Shyaway       699  Padded                 0.0   
                                            999  Padded                 0.0   

                                                             Size Count  count  
Offer            Category     Brand         MRP  Padded        

In [ ]:
tempdf["rank"] = tempdf["count"].rank()
tempdf.sort_values("count", inplace = True)

In [ ]:
tempdf

Click Cnt  \
Offer            Category   Brand          MRP  Padded                  
Buy 1 Get 1 Free Bra        Shyle          100  Padded       0.000000   
Buy 5 For 599    Sportswear United Classic 649  Padded       0.000000   
                 Bra        Enamor         1275 Padded      49.000000   
                            Inner Sense    359  Non-Padded   0.000000   
                                           389  Non-Padded   0.000000   
...                                                               ...   
                 Clothing   Shyle          249  Padded       0.402235   
                 Panty      Susie          299  Padded      33.873362   
                 Bra        Shyle          799  Padded       0.264463   
                                           699  Padded      12.756906   
                 Panty      Shyle          299  Padded       0.063312   

                                                            Sale Qty  \
Offer            Category   Brand          MRP  Padded                 
Buy 1 Get 1 Free Bra        Shyle          100  Padded      0.000000   
Buy 5 For 599    Sportswear United Classic 649  Padded      0.000000   
                 Bra        Enamor         1275 Padded      0.000000   
                            Inner Sense    359  Non-Padded  0.000000   
                                           389  Non-Padded  0.000000   
...                                                              ...   
                 Clothing   Shyle          249  Padded      0.000000   
                 Panty      Susie          299  Padded      4.161572   
                 Bra        Shyle          799  Padded      0.000000   
                                           699  Padded      0.084715   
                 Panty      Shyle          299  Padded      0.000000   

                                                            Live Stock  \
Offer            Category   Brand          MRP  Padded                   
Buy 1 Get 1 Free Bra        Shyle          100  Padded        2.000000   
Buy 5 For 599    Sportswear United Classic 649  Padded        0.000000   
                 Bra        Enamor         1275 Padded        2.000000   
                            Inner Sense    359  Non-Padded    0.000000   
                                           389  Non-Padded    0.000000   
...                                                                ...   
                 Clothing   Shyle          249  Padded        0.083799   
                 Panty      Susie          299  Padded      241.017467   
                 Bra        Shyle          799  Padded        1.128099   
                                           699  Padded        0.556169   
                 Panty      Shyle          299  Padded        0.000812   

                                                            Initital Stock  \
Offer            Category   Brand          MRP  Padded                       
Buy 1 Get 1 Free Bra        Shyle          100  Padded            0.000000   
Buy 5 For 599    Sportswear United Classic 649  Padded            0.000000   
                 Bra        Enamor         1275 Padded            0.000000   
                            Inner Sense    359  Non-Padded        0.000000   
                                           389  Non-Padded        0.000000   
...                                                                    ...   
                 Clothing   Shyle          249  Padded            0.078212   
                 Panty      Susie          299  Padded          273.344978   
                 Bra        Shyle          799  Padded            0.822314   
                                           699  Padded            0.810313   
                 Panty      Shyle          299  Padded            0.000000   

                                                            Size Count  count  \
Offer            Category   Brand          MRP  Padded                          
Buy 1 Get 1 Free Bra        Shyle

In [ ]:
tempdf=tempdf[tempdf['Size Count']>0]

In [ ]:
tempdf

Click Cnt  \
Offer                     Category   Brand          MRP  Padded                   
Buy 1 Get 1 Free          Bra        Shyle          100  Padded        0.000000   
Buy 5 For 599             Bra        Enamor         1275 Padded       49.000000   
                                     Laavian        699  Non-Padded    0.000000   
                          Sportswear United Classic 1099 Padded        0.000000   
Buy 4 For 999,Flat Rs.299 Bra        Susie          699  Padded      175.000000   
...                                                                         ...   
Buy 5 For 599             Clothing   Shyle          249  Padded        0.402235   
                          Panty      Susie          299  Padded       33.873362   
                          Bra        Shyle          799  Padded        0.264463   
                                                    699  Padded       12.756906   
                          Panty      Shyle          299  Padded        0.063312   

                                                                      Sale Qty  \
Offer                     Category   Brand          MRP  Padded                  
Buy 1 Get 1 Free          Bra        Shyle          100  Padded       0.000000   
Buy 5 For 599             Bra        Enamor         1275 Padded       0.000000   
                                     Laavian        699  Non-Padded   0.000000   
                          Sportswear United Classic 1099 Padded       0.000000   
Buy 4 For 999,Flat Rs.299 Bra        Susie          699  Padded      10.000000   
...                                                                        ...   
Buy 5 For 599             Clothing   Shyle          249  Padded       0.000000   
                          Panty      Susie          299  Padded       4.161572   
                          Bra        Shyle          799  Padded       0.000000   
                                                    699  Padded       0.084715   
                          Panty      Shyle          299  Padded       0.000000   

                                                                     Live Stock  \
Offer                     Category   Brand          MRP  Padded                   
Buy 1 Get 1 Free          Bra        Shyle          100  Padded        2.000000   
Buy 5 For 599             Bra        Enamor         1275 Padded        2.000000   
                                     Laavian        699  Non-Padded    3.000000   
                          Sportswear United Classic 1099 Padded        2.000000   
Buy 4 For 999,Flat Rs.299 Bra        Susie          699  Padded       61.000000   
...                                                                         ...   
Buy 5 For 599             Clothing   Shyle          249  Padded        0.083799   
                          Panty      Susie          299  Padded      241.017467   
                          Bra        Shyle          799  Padded        1.128099   
                                                    699  Padded        0.556169   
                          Panty      Shyle          299  Padded        0.000812   

                                                                     Initital Stock  \
Offer                     Category   Brand          MRP  Padded                       
Buy 1 Get 1 Free          Bra        Shyle          100  Padded            0.000000   
Buy 5 For 599             Bra        Enamor         1275 Padded            0.000000   
                                     Laavian        699  Non-Padded        0.000000   
                          Sportswear United Classic 1099 Padded            0.000000   
Buy 4 For 999,Flat Rs.299 Bra        Susie          699  Padded          165.000000   
...                                                                             ...   
Buy 5 For 599             Clothing   Shyle          249  Padded            0.078212   
                          Panty      Susie          299  Pad

In [ ]:
tempdf=tempdf[tempdf['Live Stock']>250]

In [ ]:
tempdf

Click Cnt  \
Offer                         Category  Brand          MRP  Padded                    
Buy 5 For 599                 Bra       Susie          599  Padded      1537.000000   
Buy 3 For 599                 Panty     Susie          549  Padded      1817.000000   
Buy 2 Get 3 Free,Flat 50% Off Bra       Shyaway        799  Padded       218.500000   
                                        Susie          949  Padded      5864.000000   
Buy 4 For 999,Flat Rs.299     Bra       Shyaway        799  Non-Padded  1172.000000   
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          999  Padded      2214.333333   
                                                       699  Non-Padded   420.250000   
                                                            Padded       381.200000   
Buy 5 For 599                 Shapewear United Classic 1299 Padded       307.833333   
Buy 4 For 999,Flat Rs.299     Bra       Susie          749  Non-Padded  1070.857143   
Buy 2 For 1299                Bra       Susie          999  Non-Padded   153.333333   
Buy 4 For 999,Flat Rs.299     Bra       Susie          799  Non-Padded   895.555556   
Buy 2 Get 3 Free,Flat 50% Off Bra       Taabu          899  Padded       820.111111   
                                        Shyaway        849  Padded      1229.111111   
                                        Susie          749  Non-Padded  1163.947368   
                                                       899  Padded      1895.718750   
                                        Taabu          799  Padded       757.909091   
                                        Susie          799  Non-Padded  1080.081081   
                                        Taabu          849  Padded       713.868421   
                                        Susie          799  Padded       526.543478   
Buy 4 For 999,Flat Rs.299     Bra       Susie          699  Non-Padded   871.541667   
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          849  Padded       548.000000   

                                                                         Sale Qty  \
Offer                         Category  Brand          MRP  Padded                  
Buy 5 For 599                 Bra       Susie          599  Padded      17.000000   
Buy 3 For 599                 Panty     Susie          549  Padded      23.000000   
Buy 2 Get 3 Free,Flat 50% Off Bra       Shyaway        799  Padded      17.500000   
                                        Susie          949  Padded      83.500000   
Buy 4 For 999,Flat Rs.299     Bra       Shyaway        799  Non-Padded  20.000000   
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          999  Padded      44.000000   
                                                       699  Non-Padded  31.250000   
                                                            Padded      13.600000   
Buy 5 For 599                 Shapewear United Classic 1299 Padded       7.666667   
Buy 4 For 999,Flat Rs.299     Bra       Susie          749  Non-Padded  29.857143   
Buy 2 For 1299                Bra       Susie          999  Non-Padded   3.000000   
Buy 4 For 999,Flat Rs.299     Bra       Susie          799  Non-Padded  31.444444   
Buy 2 Get 3 Free,Flat 50% Off Bra       Taabu          899  Padded      29.444444   
                                        Shyaway        849  Padded      32.888889   
                                        Susie          749  Non-Padded  43.315789   
                                                       899  Padded      90.812500   
                                        Taabu          799  Padded      42.666667   
                                        Susie          799  Non-Padded  47.378378   
                                        Taabu          849  Padded      35.315789   
                                        Susie          799  Padded      21.000000   
Buy 4 For 999,Flat Rs.299     Bra       Susie          699  Non-Padded  33.333333   
Buy 2 Get 3 Free,Flat 50% Off 

In [ ]:
tempdf=tempdf[tempdf['Initital Stock']>0]

In [ ]:
tempdf

Click Cnt  \
Offer                         Category  Brand          MRP  Padded                    
Buy 5 For 599                 Bra       Susie          599  Padded      1537.000000   
Buy 3 For 599                 Panty     Susie          549  Padded      1817.000000   
Buy 2 Get 3 Free,Flat 50% Off Bra       Shyaway        799  Padded       218.500000   
                                        Susie          949  Padded      5864.000000   
Buy 4 For 999,Flat Rs.299     Bra       Shyaway        799  Non-Padded  1172.000000   
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          999  Padded      2214.333333   
                                                       699  Non-Padded   420.250000   
                                                            Padded       381.200000   
Buy 5 For 599                 Shapewear United Classic 1299 Padded       307.833333   
Buy 4 For 999,Flat Rs.299     Bra       Susie          749  Non-Padded  1070.857143   
Buy 2 For 1299                Bra       Susie          999  Non-Padded   153.333333   
Buy 4 For 999,Flat Rs.299     Bra       Susie          799  Non-Padded   895.555556   
Buy 2 Get 3 Free,Flat 50% Off Bra       Taabu          899  Padded       820.111111   
                                        Shyaway        849  Padded      1229.111111   
                                        Susie          749  Non-Padded  1163.947368   
                                                       899  Padded      1895.718750   
                                        Taabu          799  Padded       757.909091   
                                        Susie          799  Non-Padded  1080.081081   
                                        Taabu          849  Padded       713.868421   
                                        Susie          799  Padded       526.543478   
Buy 4 For 999,Flat Rs.299     Bra       Susie          699  Non-Padded   871.541667   
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          849  Padded       548.000000   

                                                                         Sale Qty  \
Offer                         Category  Brand          MRP  Padded                  
Buy 5 For 599                 Bra       Susie          599  Padded      17.000000   
Buy 3 For 599                 Panty     Susie          549  Padded      23.000000   
Buy 2 Get 3 Free,Flat 50% Off Bra       Shyaway        799  Padded      17.500000   
                                        Susie          949  Padded      83.500000   
Buy 4 For 999,Flat Rs.299     Bra       Shyaway        799  Non-Padded  20.000000   
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          999  Padded      44.000000   
                                                       699  Non-Padded  31.250000   
                                                            Padded      13.600000   
Buy 5 For 599                 Shapewear United Classic 1299 Padded       7.666667   
Buy 4 For 999,Flat Rs.299     Bra       Susie          749  Non-Padded  29.857143   
Buy 2 For 1299                Bra       Susie          999  Non-Padded   3.000000   
Buy 4 For 999,Flat Rs.299     Bra       Susie          799  Non-Padded  31.444444   
Buy 2 Get 3 Free,Flat 50% Off Bra       Taabu          899  Padded      29.444444   
                                        Shyaway        849  Padded      32.888889   
                                        Susie          749  Non-Padded  43.315789   
                                                       899  Padded      90.812500   
                                        Taabu          799  Padded      42.666667   
                                        Susie          799  Non-Padded  47.378378   
                                        Taabu          849  Padded      35.315789   
                                        Susie          799  Padded      21.000000   
Buy 4 For 999,Flat Rs.299     Bra       Susie          699  Non-Padded  33.333333   
Buy 2 Get 3 Free,Flat 50% Off 

In [ ]:
tempdf.count()

Click Cnt         22
Sale Qty          22
Live Stock        22
Initital Stock    22
Size Count        22
count             22
rank              22
dtype: int64

In [ ]:
tempdf['diff'] = tempdf['Initital Stock'] - (tempdf['Live Stock'] + tempdf['Sale Qty'])

In [ ]:
tempdf['diff']

Offer                          Category   Brand           MRP   Padded    
Buy 5 For 599                  Bra        Susie           599   Padded         37.000000
Buy 3 For 599                  Panty      Susie           549   Padded         82.000000
Buy 2 Get 3 Free,Flat 50% Off  Bra        Shyaway         799   Padded         46.500000
                                          Susie           949   Padded         19.000000
Buy 4 For 999,Flat Rs.299      Bra        Shyaway         799   Non-Padded    142.000000
Buy 2 Get 3 Free,Flat 50% Off  Bra        Susie           999   Padded         36.333333
                                                          699   Non-Padded    180.750000
                                                                Padded         22.600000
Buy 5 For 599                  Shapewear  United Classic  1299  Padded         31.166667
Buy 4 For 999,Flat Rs.299      Bra        Susie           749   Non-Padded    153.000000
Buy 2 For 1299                 Bra 

In [ ]:
tempdf['Return Percentage']=(tempdf['diff'] / tempdf['Initital Stock']) * 100.0

In [ ]:
tempdf

Click Cnt  \
Offer                         Category  Brand          MRP  Padded                    
Buy 5 For 599                 Bra       Susie          599  Padded      1537.000000   
Buy 3 For 599                 Panty     Susie          549  Padded      1817.000000   
Buy 2 Get 3 Free,Flat 50% Off Bra       Shyaway        799  Padded       218.500000   
                                        Susie          949  Padded      5864.000000   
Buy 4 For 999,Flat Rs.299     Bra       Shyaway        799  Non-Padded  1172.000000   
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          999  Padded      2214.333333   
                                                       699  Non-Padded   420.250000   
                                                            Padded       381.200000   
Buy 5 For 599                 Shapewear United Classic 1299 Padded       307.833333   
Buy 4 For 999,Flat Rs.299     Bra       Susie          749  Non-Padded  1070.857143   
Buy 2 For 1299                Bra       Susie          999  Non-Padded   153.333333   
Buy 4 For 999,Flat Rs.299     Bra       Susie          799  Non-Padded   895.555556   
Buy 2 Get 3 Free,Flat 50% Off Bra       Taabu          899  Padded       820.111111   
                                        Shyaway        849  Padded      1229.111111   
                                        Susie          749  Non-Padded  1163.947368   
                                                       899  Padded      1895.718750   
                                        Taabu          799  Padded       757.909091   
                                        Susie          799  Non-Padded  1080.081081   
                                        Taabu          849  Padded       713.868421   
                                        Susie          799  Padded       526.543478   
Buy 4 For 999,Flat Rs.299     Bra       Susie          699  Non-Padded   871.541667   
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          849  Padded       548.000000   

                                                                         Sale Qty  \
Offer                         Category  Brand          MRP  Padded                  
Buy 5 For 599                 Bra       Susie          599  Padded      17.000000   
Buy 3 For 599                 Panty     Susie          549  Padded      23.000000   
Buy 2 Get 3 Free,Flat 50% Off Bra       Shyaway        799  Padded      17.500000   
                                        Susie          949  Padded      83.500000   
Buy 4 For 999,Flat Rs.299     Bra       Shyaway        799  Non-Padded  20.000000   
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          999  Padded      44.000000   
                                                       699  Non-Padded  31.250000   
                                                            Padded      13.600000   
Buy 5 For 599                 Shapewear United Classic 1299 Padded       7.666667   
Buy 4 For 999,Flat Rs.299     Bra       Susie          749  Non-Padded  29.857143   
Buy 2 For 1299                Bra       Susie          999  Non-Padded   3.000000   
Buy 4 For 999,Flat Rs.299     Bra       Susie          799  Non-Padded  31.444444   
Buy 2 Get 3 Free,Flat 50% Off Bra       Taabu          899  Padded      29.444444   
                                        Shyaway        849  Padded      32.888889   
                                        Susie          749  Non-Padded  43.315789   
                                                       899  Padded      90.812500   
                                        Taabu          799  Padded      42.666667   
                                        Susie          799  Non-Padded  47.378378   
                                        Taabu          849  Padded      35.315789   
                                        Susie          799  Padded      21.000000   
Buy 4 For 999,Flat Rs.299     Bra       Susie          699  Non-Padded  33.333333   
Buy 2 Get 3 Free,Flat 50% Off 

In [ ]:
tempdf['Return Percentage'].mean()

12.079957088306037

In [ ]:
tempdf["Final Ranking"] = tempdf["Return Percentage"].rank()
tempdf.sort_values("Return Percentage", inplace = True)

In [ ]:
tempdf

Click Cnt  \
Offer                         Category  Brand          MRP  Padded                    
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          949  Padded      5864.000000   
Buy 2 For 1299                Bra       Susie          999  Non-Padded   153.333333   
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          699  Padded       381.200000   
                                        Shyaway        849  Padded      1229.111111   
Buy 3 For 599                 Panty     Susie          549  Padded      1817.000000   
Buy 5 For 599                 Shapewear United Classic 1299 Padded       307.833333   
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          999  Padded      2214.333333   
                                                       799  Padded       526.543478   
                                        Shyaway        799  Padded       218.500000   
Buy 5 For 599                 Bra       Susie          599  Padded      1537.000000   
Buy 2 Get 3 Free,Flat 50% Off Bra       Taabu          899  Padded       820.111111   
                                                       799  Padded       757.909091   
                                        Susie          849  Padded       548.000000   
                                                       899  Padded      1895.718750   
                                                       799  Non-Padded  1080.081081   
                                        Taabu          849  Padded       713.868421   
                                        Susie          749  Non-Padded  1163.947368   
Buy 4 For 999,Flat Rs.299     Bra       Susie          749  Non-Padded  1070.857143   
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          699  Non-Padded   420.250000   
Buy 4 For 999,Flat Rs.299     Bra       Shyaway        799  Non-Padded  1172.000000   
                                        Susie          699  Non-Padded   871.541667   
                                                       799  Non-Padded   895.555556   

                                                                         Sale Qty  \
Offer                         Category  Brand          MRP  Padded                  
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          949  Padded      83.500000   
Buy 2 For 1299                Bra       Susie          999  Non-Padded   3.000000   
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          699  Padded      13.600000   
                                        Shyaway        849  Padded      32.888889   
Buy 3 For 599                 Panty     Susie          549  Padded      23.000000   
Buy 5 For 599                 Shapewear United Classic 1299 Padded       7.666667   
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          999  Padded      44.000000   
                                                       799  Padded      21.000000   
                                        Shyaway        799  Padded      17.500000   
Buy 5 For 599                 Bra       Susie          599  Padded      17.000000   
Buy 2 Get 3 Free,Flat 50% Off Bra       Taabu          899  Padded      29.444444   
                                                       799  Padded      42.666667   
                                        Susie          849  Padded      25.729167   
                                                       899  Padded      90.812500   
                                                       799  Non-Padded  47.378378   
                                        Taabu          849  Padded      35.315789   
                                        Susie          749  Non-Padded  43.315789   
Buy 4 For 999,Flat Rs.299     Bra       Susie          749  Non-Padded  29.857143   
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          699  Non-Padded  31.250000   
Buy 4 For 999,Flat Rs.299     Bra       Shyaway        799  Non-Padded  20.000000   
                                        Susie          699  Non-Padded  33.333333   
                              

# To download the Final Ranking list

In [ ]:
tempdf1=tempdf

In [ ]:
from IPython.display import HTML

In [ ]:
tempdff1 = pd.DataFrame(tempdf1)
# tempdf1 = pd.DataFrame(np.arange(1000), columns=['data'])

tempdff1.to_csv('submission.csv')


# print('DataFrame:\n', tempdff1)

# # default CSV
# csv_data = tempdff1.to_csv()
# print('\nCSV String:\n', csv_data)

In [ ]:
def create_download_link(title = "Download CSV file", filename = "data.csv"):  
    html = '<a href={filename}>{title}</a>'
    html = html.format(title=title,filename=filename)
    return HTML(html)

# create a link to download the dataframe which was saved with .to_csv method
create_download_link(filename='submission.csv')

# Combine

In [ ]:
tempdf=df1

dff2 = tempdf.groupby(["Offer", "Category", "Brand", "MRP", "Padded"])

tempdf=dff2.agg({'Click Cnt':'mean', 'Sale Qty':'mean','Live Stock':'mean','Initital Stock':'mean','Size Count':'mean'}).rename(columns={'Click Cnt':'Click Cnt', 'Sale Qty':'Sale Qty','Live Stock':'Live Stock', 'Initital Stock':'Initital Stock','Size Count':'Size Count'})

tempdf['count'] = dff2.size()

tempdf["rank"] = tempdf["count"].rank()
tempdf.sort_values("count", inplace = True)

tempdf=tempdf[tempdf['Size Count']>0]

tempdf=tempdf[tempdf['Live Stock']>250]

tempdf=tempdf[tempdf['Initital Stock']>0]

tempdf['diff'] = tempdf['Initital Stock'] - (tempdf['Live Stock'] + tempdf['Sale Qty'])

tempdf['Return Percentage']=(tempdf['diff'] / tempdf['Initital Stock']) * 100.0

print(tempdf['Return Percentage'].mean())

tempdf["Final Ranking"] = tempdf["Return Percentage"].rank()
tempdf.sort_values("Return Percentage", inplace = True)

print(tempdf)

tempdf1=tempdf

from IPython.display import HTML

tempdff1 = pd.DataFrame(tempdf1)
# tempdf1 = pd.DataFrame(np.arange(1000), columns=['data'])

tempdff1.to_csv('submission.csv')


# print('DataFrame:\n', tempdff1)

# # default CSV
# csv_data = tempdff1.to_csv()
# print('\nCSV String:\n', csv_data)

def create_download_link(title = "Download CSV file", filename = "data.csv"):  
    html = '<a href={filename}>{title}</a>'
    html = html.format(title=title,filename=filename)
    return HTML(html)

# create a link to download the dataframe which was saved with .to_csv method
create_download_link(filename='submission.csv')

12.079957088306037
                                                                          Click Cnt  \
Offer                         Category  Brand          MRP  Padded                    
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          949  Padded      5864.000000   
Buy 2 For 1299                Bra       Susie          999  Non-Padded   153.333333   
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          699  Padded       381.200000   
                                        Shyaway        849  Padded      1229.111111   
Buy 3 For 599                 Panty     Susie          549  Padded      1817.000000   
Buy 5 For 599                 Shapewear United Classic 1299 Padded       307.833333   
Buy 2 Get 3 Free,Flat 50% Off Bra       Susie          999  Padded      2214.333333   
                                                       799  Padded       526.543478   
                                        Shyaway        799  Padded       218.500000   
Buy 5 For 599           